### ISSUE TITLE
局域网内所有的主机和主机名是怎么获取的

### ISSUE THREAD

**Issue by JonkMing** [ssun125/Lanmitm#4]
最近在研究这个,但我直接取arp 文件中的数据,只能取到Ip 和 Mac 地址,但网上大多数的分析软件都能获取到主机名~~~

**Comment by ssun125** [comment]
请看：https://github.com/ssun125/Lanmitm/blob/master/src/com/oinux/lanmitm/ui/HostsActivity.java
UDPThread发送的NETBIOS数据包
